/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/servers/{server_id}/invites': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Invites */
    get: operations['list_invites_api_servers__server_id__invites_get']
    put?: never
    /** Create Invite */
    post: operations['create_invite_api_servers__server_id__invites_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/invites/{key}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Invite Info */
    get: operations['get_invite_info_api_servers_invites__key__get']
    put?: never
    /** Use Invite */
    post: operations['use_invite_api_servers_invites__key__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/invites/{invite_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Revoke Invite */
    delete: operations['revoke_invite_api_servers__server_id__invites__invite_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/games/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Server Games */
    get: operations['list_server_games_api_servers__server_id__games__get']
    put?: never
    /** Add Game To Server */
    post: operations['add_game_to_server_api_servers__server_id__games__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/games/{game_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove Game From Server */
    delete: operations['remove_game_from_server_api_servers__server_id__games__game_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/role-set/{role_set_id}/roles': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Role */
    post: operations['create_role_api_servers__server_id__role_set__role_set_id__roles_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/role-set/{role_set_id}/roles/{role_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Role */
    delete: operations['delete_role_api_servers__server_id__role_set__role_set_id__roles__role_id__delete']
    options?: never
    head?: never
    /** Update Role */
    patch: operations['update_role_api_servers__server_id__role_set__role_set_id__roles__role_id__patch']
    trace?: never
  }
  '/api/servers/{server_id}/role-set/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Role Set */
    get: operations['get_role_set_api_servers__server_id__role_set__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/role-set/{role_set_id}/roles/{role_id}/icon': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update Role Icon */
    put: operations['update_role_icon_api_servers__server_id__role_set__role_set_id__roles__role_id__icon_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/role-set/{role_set_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Role Set */
    patch: operations['update_role_set_api_servers__server_id__role_set__role_set_id__patch']
    trace?: never
  }
  '/api/servers/{server_id}/rating-set/{rating_set_id}/ratings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Rating */
    post: operations['create_rating_api_servers__server_id__rating_set__rating_set_id__ratings_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/rating-set/{rating_set_id}/ratings/{rating_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Rating */
    delete: operations['delete_rating_api_servers__server_id__rating_set__rating_set_id__ratings__rating_id__delete']
    options?: never
    head?: never
    /** Update Rating */
    patch: operations['update_rating_api_servers__server_id__rating_set__rating_set_id__ratings__rating_id__patch']
    trace?: never
  }
  '/api/servers/{server_id}/rating-set/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Rating Set */
    get: operations['get_rating_set_api_servers__server_id__rating_set__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/rating-set/{rating_set_id}/ratings/{rating_id}/icon': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update Rating Icon */
    put: operations['update_rating_icon_api_servers__server_id__rating_set__rating_set_id__ratings__rating_id__icon_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/rating-set/{rating_set_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Rating Set */
    patch: operations['update_rating_set_api_servers__server_id__rating_set__rating_set_id__patch']
    trace?: never
  }
  '/api/servers/{server_id}/members/{member_id}/customs/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Customs */
    get: operations['list_customs_api_servers__server_id__members__member_id__customs__get']
    put?: never
    /** Create Custom */
    post: operations['create_custom_api_servers__server_id__members__member_id__customs__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/members/{member_id}/customs/{custom_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Custom */
    get: operations['get_custom_api_servers__server_id__members__member_id__customs__custom_id__get']
    put?: never
    post?: never
    /** Delete Custom */
    delete: operations['delete_custom_api_servers__server_id__members__member_id__customs__custom_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/members/{member_id}/customs/{custom_id}/ratings/{game_role_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update Rating Value */
    put: operations['update_rating_value_api_servers__server_id__members__member_id__customs__custom_id__ratings__game_role_id__put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/members/{member_id}/restrictions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Restrictions */
    get: operations['get_restrictions_api_servers__server_id__members__member_id__restrictions_get']
    put?: never
    /** Add Restriction */
    post: operations['add_restriction_api_servers__server_id__members__member_id__restrictions_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/members/virtual': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Virtual */
    post: operations['create_virtual_api_servers__server_id__members_virtual_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/members/{member_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Member */
    get: operations['get_member_api_servers__server_id__members__member_id__get']
    put?: never
    post?: never
    /** Kick Member */
    delete: operations['kick_member_api_servers__server_id__members__member_id__delete']
    options?: never
    head?: never
    /** Update Member */
    patch: operations['update_member_api_servers__server_id__members__member_id__patch']
    trace?: never
  }
  '/api/servers/{server_id}/members/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Members */
    get: operations['list_members_api_servers__server_id__members__get']
    put?: never
    /** Join Server */
    post: operations['join_server_api_servers__server_id__members__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/members/{member_id}/migrate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Migrate Member */
    post: operations['migrate_member_api_servers__server_id__members__member_id__migrate_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/members/{member_id}/restrictions/{member_restriction_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove Restriction */
    delete: operations['remove_restriction_api_servers__server_id__members__member_id__restrictions__member_restriction_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List User Servers */
    get: operations['list_user_servers_api_servers__get']
    put?: never
    /** Create Server */
    post: operations['create_server_api_servers__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Server */
    get: operations['get_server_api_servers__server_id__get']
    put?: never
    post?: never
    /** Delete Server */
    delete: operations['delete_server_api_servers__server_id__delete']
    options?: never
    head?: never
    /** Update Server */
    patch: operations['update_server_api_servers__server_id__patch']
    trace?: never
  }
  '/api/servers/games': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Global Games */
    get: operations['get_global_games_api_servers_games_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/rating-set': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Global Rating Templates */
    get: operations['get_global_rating_templates_api_servers_rating_set_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/restrictions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Global Restrictions */
    get: operations['get_global_restrictions_api_servers_restrictions_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/role-set': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Global Role Templates */
    get: operations['get_global_role_templates_api_servers_role_set_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/banner': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update Banner */
    put: operations['update_banner_api_servers__server_id__banner_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{server_id}/icon': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update Icon */
    put: operations['update_icon_api_servers__server_id__icon_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Body_create_rating_api_servers__server_id__rating_set__rating_set_id__ratings_post */
    Body_create_rating_api_servers__server_id__rating_set__rating_set_id__ratings_post: {
      body: components['schemas']['RatingItemCreateRequest']
      /**
       * Icon
       * Format: binary
       */
      icon: string
    }
    /** Body_create_role_api_servers__server_id__role_set__role_set_id__roles_post */
    Body_create_role_api_servers__server_id__role_set__role_set_id__roles_post: {
      body: components['schemas']['GameRoleItemCreateRequest']
      /**
       * Icon
       * Format: binary
       */
      icon: string
    }
    /** Body_update_banner_api_servers__server_id__banner_put */
    Body_update_banner_api_servers__server_id__banner_put: {
      /**
       * Banner
       * Format: binary
       */
      banner: string
    }
    /** Body_update_icon_api_servers__server_id__icon_put */
    Body_update_icon_api_servers__server_id__icon_put: {
      /**
       * Icon
       * Format: binary
       */
      icon: string
    }
    /** Body_update_rating_icon_api_servers__server_id__rating_set__rating_set_id__ratings__rating_id__icon_put */
    Body_update_rating_icon_api_servers__server_id__rating_set__rating_set_id__ratings__rating_id__icon_put: {
      /**
       * Icon
       * Format: binary
       */
      icon: string
    }
    /** Body_update_role_icon_api_servers__server_id__role_set__role_set_id__roles__role_id__icon_put */
    Body_update_role_icon_api_servers__server_id__role_set__role_set_id__roles__role_id__icon_put: {
      /**
       * Icon
       * Format: binary
       */
      icon: string
    }
    /** CustomRatingResponse */
    CustomRatingResponse: {
      game_role: components['schemas']['GameRoleItemResponse']
      /** Rating */
      rating: number
    }
    /** CustomResponse */
    CustomResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Custom Ratings */
      custom_ratings: components['schemas']['CustomRatingResponse'][]
    }
    /** GameAddRequest */
    GameAddRequest: {
      /** Ids */
      ids: string[]
    }
    /** GameResponse */
    GameResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Icon Url */
      icon_url: string
      /** Banner Url */
      banner_url: string
    }
    /** GameRoleItemCreateRequest */
    GameRoleItemCreateRequest: {
      /** Name */
      name: string
      /** Min In Team */
      min_in_team: number
      /** Max In Team */
      max_in_team: number
      /**
       * Hidden
       * @default false
       */
      hidden: boolean
    }
    /** GameRoleItemResponse */
    GameRoleItemResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Icon Url */
      icon_url?: string | null
      /** Min In Team */
      min_in_team: number
      /** Max In Team */
      max_in_team: number
      /** Hidden */
      hidden: boolean
    }
    /** GameRoleItemUpdateRequest */
    GameRoleItemUpdateRequest: {
      /** Name */
      name?: string | null
      /** Min In Team */
      min_in_team?: number | null
      /** Max In Team */
      max_in_team?: number | null
      /** Hidden */
      hidden?: boolean | null
    }
    /** GameRoleRatingSetRequest */
    GameRoleRatingSetRequest: {
      /** Rating */
      rating: number
    }
    /** GameRoleSetResponse */
    GameRoleSetResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /**
       * Game Roles
       * @default []
       */
      game_roles: components['schemas']['GameRoleItemResponse'][]
    }
    /** GameRoleSetUpdateRequest */
    GameRoleSetUpdateRequest: {
      /** Name */
      name?: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** InviteAdminResponse */
    InviteAdminResponse: {
      /** Key */
      key: string
      /**
       * Inviter Id
       * Format: uuid
       */
      inviter_id: string
      /** Use Limit */
      use_limit: number
    }
    /** InviteCreateRequest */
    InviteCreateRequest: {
      /** Use Limit */
      use_limit?: number | null
    }
    /** InviteKeyResponse */
    InviteKeyResponse: {
      server: components['schemas']['ServerListResponse']
    }
    /** MemberResponse */
    MemberResponse: {
      /** Name */
      name: string
      /** User Id */
      user_id: string | null
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string
      server_role: components['schemas']['ServerRoleResponse'] | null
    }
    /** MemberRestrictionCreateRequest */
    MemberRestrictionCreateRequest: {
      /** Reason */
      reason: string
      /**
       * Expiration Date
       * Format: date-time
       */
      expiration_date: string
      /**
       * Restriction Id
       * Format: uuid
       */
      restriction_id: string
    }
    /** MemberRestrictionResponse */
    MemberRestrictionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Reason */
      reason: string
      /**
       * Expiration Date
       * Format: date-time
       */
      expiration_date: string
      restriction: components['schemas']['RestrictionResponse']
    }
    /** MemberUpdateRequest */
    MemberUpdateRequest: {
      /** Name */
      name: string
      /** User Id */
      user_id?: string | null
      /** Server Role Id */
      server_role_id?: string | null
    }
    /** MigrationRequest */
    MigrationRequest: {
      /**
       * Target Member Id
       * Format: uuid
       */
      target_member_id: string
    }
    /** RatingItemCreateRequest */
    RatingItemCreateRequest: {
      /** Threshold */
      threshold: number
    }
    /** RatingItemResponse */
    RatingItemResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Icon Url */
      icon_url: string
      /** Threshold */
      threshold: number
    }
    /** RatingItemUpdateRequest */
    RatingItemUpdateRequest: {
      /** Threshold */
      threshold?: number | null
    }
    /** RatingSetResponse */
    RatingSetResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Min Rating */
      min_rating: number
      /** Max Rating */
      max_rating: number
      /** Is Global */
      is_global: boolean
      /**
       * Ratings
       * @default []
       */
      ratings: components['schemas']['RatingItemResponse'][]
    }
    /** RatingSetUpdateRequest */
    RatingSetUpdateRequest: {
      /** Name */
      name?: string | null
      /** Min Rating */
      min_rating?: number | null
      /** Max Rating */
      max_rating?: number | null
    }
    /** RestrictionResponse */
    RestrictionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Type Code */
      type_code: string
    }
    /** ServerCreateRequest */
    ServerCreateRequest: {
      /** Name */
      name: string
      /**
       * Description
       * @default
       */
      description: string
      /** Public */
      public: boolean
      /** Rating Set Id */
      rating_set_id?: string | null
      /** Role Set Id */
      role_set_id?: string | null
      /**
       * Game Ids
       * @default []
       */
      game_ids: string[]
    }
    /** ServerDetailResponse */
    ServerDetailResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Description */
      description: string
      /** Icon Url */
      icon_url?: string | null
      /** Banner Url */
      banner_url?: string | null
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string
      /** Public */
      public: boolean
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      rating_set?: components['schemas']['RatingSetResponse'] | null
      role_set?: components['schemas']['GameRoleSetResponse'] | null
      /**
       * Games
       * @default []
       */
      games: components['schemas']['GameResponse'][]
    }
    /** ServerListResponse */
    ServerListResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Description */
      description: string
      /** Icon Url */
      icon_url?: string | null
      /** Banner Url */
      banner_url?: string | null
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string
      /** Public */
      public: boolean
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** ServerPermissionResponse */
    ServerPermissionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Code Name */
      code_name: string
    }
    /** ServerRoleResponse */
    ServerRoleResponse: {
      /** Name */
      name: string
      /** Position */
      position: number
      /** Permissions */
      permissions: components['schemas']['ServerPermissionResponse'][]
    }
    /** ServerUpdateRequest */
    ServerUpdateRequest: {
      /** Name */
      name?: string | null
      /** Description */
      description?: string | null
      /** Public */
      public?: boolean | null
    }
    /** StatusResponse */
    StatusResponse: {
      /**
       * Status
       * @default ok
       */
      status: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /** VirtualMemberCreateRequest */
    VirtualMemberCreateRequest: {
      /** Name */
      name: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_invites_api_servers__server_id__invites_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InviteAdminResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_invite_api_servers__server_id__invites_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InviteCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_invite_info_api_servers_invites__key__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        key: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InviteKeyResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  use_invite_api_servers_invites__key__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        key: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  revoke_invite_api_servers__server_id__invites__invite_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        invite_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_server_games_api_servers__server_id__games__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  add_game_to_server_api_servers__server_id__games__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GameAddRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  remove_game_from_server_api_servers__server_id__games__game_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_role_api_servers__server_id__role_set__role_set_id__roles_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        role_set_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_create_role_api_servers__server_id__role_set__role_set_id__roles_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_role_api_servers__server_id__role_set__role_set_id__roles__role_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        role_set_id: string
        role_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_role_api_servers__server_id__role_set__role_set_id__roles__role_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        role_set_id: string
        role_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GameRoleItemUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameRoleItemResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_role_set_api_servers__server_id__role_set__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameRoleSetResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_role_icon_api_servers__server_id__role_set__role_set_id__roles__role_id__icon_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        role_id: string
        role_set_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_update_role_icon_api_servers__server_id__role_set__role_set_id__roles__role_id__icon_put']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameRoleItemResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_role_set_api_servers__server_id__role_set__role_set_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        role_set_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GameRoleSetUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameRoleSetResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_rating_api_servers__server_id__rating_set__rating_set_id__ratings_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        rating_set_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_create_rating_api_servers__server_id__rating_set__rating_set_id__ratings_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RatingItemResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_rating_api_servers__server_id__rating_set__rating_set_id__ratings__rating_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        rating_set_id: string
        rating_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_rating_api_servers__server_id__rating_set__rating_set_id__ratings__rating_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        rating_set_id: string
        rating_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RatingItemUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RatingItemResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_rating_set_api_servers__server_id__rating_set__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RatingSetResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_rating_icon_api_servers__server_id__rating_set__rating_set_id__ratings__rating_id__icon_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        rating_set_id: string
        rating_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_update_rating_icon_api_servers__server_id__rating_set__rating_set_id__ratings__rating_id__icon_put']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RatingItemResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_rating_set_api_servers__server_id__rating_set__rating_set_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        rating_set_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RatingSetUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RatingSetResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_customs_api_servers__server_id__members__member_id__customs__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        member_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CustomResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_custom_api_servers__server_id__members__member_id__customs__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        member_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CustomResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_custom_api_servers__server_id__members__member_id__customs__custom_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        member_id: string
        custom_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CustomResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_custom_api_servers__server_id__members__member_id__customs__custom_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        member_id: string
        custom_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_rating_value_api_servers__server_id__members__member_id__customs__custom_id__ratings__game_role_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        member_id: string
        custom_id: string
        game_role_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GameRoleRatingSetRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CustomResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_restrictions_api_servers__server_id__members__member_id__restrictions_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        member_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberRestrictionResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  add_restriction_api_servers__server_id__members__member_id__restrictions_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        member_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MemberRestrictionCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberRestrictionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_virtual_api_servers__server_id__members_virtual_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VirtualMemberCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_member_api_servers__server_id__members__member_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        member_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  kick_member_api_servers__server_id__members__member_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        member_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_member_api_servers__server_id__members__member_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        member_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MemberUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_members_api_servers__server_id__members__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  join_server_api_servers__server_id__members__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  migrate_member_api_servers__server_id__members__member_id__migrate_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        member_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MigrationRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  remove_restriction_api_servers__server_id__members__member_id__restrictions__member_restriction_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
        member_id: string
        member_restriction_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_user_servers_api_servers__get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServerListResponse'][]
        }
      }
    }
  }
  create_server_api_servers__post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ServerCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_server_api_servers__server_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServerDetailResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_server_api_servers__server_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_server_api_servers__server_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ServerUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServerDetailResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_global_games_api_servers_games_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameResponse'][]
        }
      }
    }
  }
  get_global_rating_templates_api_servers_rating_set_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RatingSetResponse'][]
        }
      }
    }
  }
  get_global_restrictions_api_servers_restrictions_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RestrictionResponse'][]
        }
      }
    }
  }
  get_global_role_templates_api_servers_role_set_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameRoleSetResponse'][]
        }
      }
    }
  }
  update_banner_api_servers__server_id__banner_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_update_banner_api_servers__server_id__banner_put']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServerDetailResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_icon_api_servers__server_id__icon_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        server_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_update_icon_api_servers__server_id__icon_put']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServerDetailResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
