export const PERMISSION_CODES = {
  // Members
  KICK_MEMBERS: 'kick_members',
  MANAGE_NICKNAMES: 'manage_nicknames',
  MANAGE_ROLES: 'manage_roles',

  // Virtual members
  CREATE_VIRTUAL_MEMBER: 'create_virtual_member',
  MIGRATE_VIRTUAL_MEMBER: 'migrate_members',

  // Restrictions
  VIEW_RESTRICTIONS: 'view_restrictions',
  MANAGE_RESTRICTIONS: 'manage_restrictions',

  // Server
  MANAGE_SERVER: 'manage_server',
  MANAGE_INVITES: 'manage_invites',

  // Admin
  ADMINISTRATOR: 'administrator',
} as const

export type PermissionCode = (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES]

export const ACTIONS = {
  KICK_MEMBER: [PERMISSION_CODES.KICK_MEMBERS, PERMISSION_CODES.ADMINISTRATOR],
  EDIT_NICKNAME: [PERMISSION_CODES.MANAGE_NICKNAMES, PERMISSION_CODES.ADMINISTRATOR],
  CHANGE_ROLE: [PERMISSION_CODES.MANAGE_ROLES, PERMISSION_CODES.ADMINISTRATOR],
  CREATE_VIRTUAL: [PERMISSION_CODES.CREATE_VIRTUAL_MEMBER, PERMISSION_CODES.ADMINISTRATOR],
  MIGRATE_VIRTUAL: [PERMISSION_CODES.MIGRATE_VIRTUAL_MEMBER, PERMISSION_CODES.ADMINISTRATOR],
  VIEW_RESTRICTIONS: [PERMISSION_CODES.VIEW_RESTRICTIONS, PERMISSION_CODES.ADMINISTRATOR],
  MANAGE_RESTRICTIONS: [PERMISSION_CODES.MANAGE_RESTRICTIONS, PERMISSION_CODES.ADMINISTRATOR],
  MANAGE_SERVER: [PERMISSION_CODES.MANAGE_SERVER, PERMISSION_CODES.ADMINISTRATOR],
  MANAGE_INVITES: [PERMISSION_CODES.MANAGE_INVITES, PERMISSION_CODES.ADMINISTRATOR],
} as const

export type ActionKey = keyof typeof ACTIONS
