FROM node:20-alpine AS builder

WORKDIR '/app'

COPY package*.json pnpm-lock.yaml* ./

RUN npm i -g pnpm 

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build

FROM nginx:stable AS production

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]